version: '3.8'
services:
  application:
    image: euclid1990/ubuntu-server
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - "3305:3306"
    environment:
      TZ: Asia/Ho_Chi_Minh
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuel_demo
      MYSQL_USER: guest
      MYSQL_PASSWORD: 123456Aa@
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile-fpm
    ports:
      - "9695:9000"
    volumes_from:
      - application
    depends_on:
      - mysql

  nginx:
    image: nginx
    ports:
      - "8695:80"
    depends_on:
      - php
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx_conf:/etc/nginx/conf.d

volumes:
  mysql_data:
