FROM php:8.1-fpm

# Cài đặt locales và tạo en_US.UTF-8
RUN apt-get update && \
    apt-get install -y locales && \
    sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=en_US.UTF-8

# Thiết lập biến môi trường cho locale
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Cài thêm extensions PHP nếu cần
RUN docker-php-ext-install pdo pdo_mysql